# Generated by Django 4.0.5 on 2022-06-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('verification_code', models.CharField(max_length=8)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=0)),
                ('update_at', models.DateTimeField(null=True)),
                ('removed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.BigIntegerField(max_length=20)),
                ('user', models.BigIntegerField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(default=0)),
            ],
            options={
                'db_table': 'app_weather',
            },
        ),
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_weather_type',
            },
        ),
    ]
