# Generated by Django 4.0 on 2022-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_alter_weather_user_alter_weather_weather_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='lat',
            field=models.FloatField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='long',
            field=models.FloatField(default='0', null=True),
        ),
    ]
