# Generated by Django 4.0.6 on 2022-07-20 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0005_alter_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 22, 28, 41, 446333)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 7, 20, 22, 28, 41, 446333)),
        ),
    ]
