# Generated by Django 4.0.6 on 2022-07-20 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0006_alter_appuser_created_at_alter_appuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='long',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 22, 32, 42, 654480)),
        ),
    ]
